api.connect_success :
    path     : /success
    methods  : GET
    defaults :
        _controller: \Chuck\App\Api\Controller\ConnectController::successAction

api.connect_slack :
    path     : /slack
    methods  : GET
    defaults :
        _controller: \Chuck\App\Api\Controller\Connect\SlackController::connectAction